version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: sit_nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - gitea
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: sit_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://127.0.0.1:3000/
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=supersecret
    volumes:
      - gitea_data:/data
    ports:
      - "127.0.0.1:3000:3000" # Web UI
      - "127.0.0.1:222:22"    # SSH
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sit_sonarqube
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

volumes:
  gitea_data:
  sonarqube_data:
  sonarqube_extensions:
